name: Auto Approve

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Auto-approved by GitHub Actions."
